const products = [
  {
    id: 1,
    name: "Smartphone",
    brand: "Apple",
    price: 599.99,
    description: "A high-end smartphone with advanced features.",
    color: "Black",
    in_stock: true,
  },
  {
    id: 2,
    name: "Laptop",
    brand: "Asus",
    price: 1299.99,
    description: "Powerful laptop for gaming and productivity.",
    color: "Silver",
    in_stock: true,
  },
  {
    id: 3,
    name: "Smartwatch",
    brand: "Apple",
    price: 249.99,
    description: "Fitness tracker with heart rate monitoring and GPS.",
    color: "Blue",
    in_stock: true,
  },
  {
    id: 4,
    name: "Tablet",
    brand: "Lenovo",
    price: 399.99,
    description: "Slim and lightweight tablet for entertainment and work.",
    color: "Gold",
    in_stock: false,
  },
  {
    id: 5,
    name: "Wireless Headphones",
    brand: "JKL",
    price: 149.99,
    description: "Noise-canceling headphones with long battery life.",
    color: "White",
    in_stock: true,
  },
  {
    id: 6,
    name: "Gaming Console",
    brand: "Xbox",
    price: 499.99,
    description: "Next-gen gaming console with 4K support.",
    color: "Black",
    in_stock: true,
  },
  {
    id: 7,
    name: "Wireless Router",
    brand: "LINK",
    price: 79.99,
    description: "High-speed router for seamless internet connectivity.",
    color: "Black",
    in_stock: true,
  },
  {
    id: 8,
    name: "Smart Speaker",
    brand: "OneMic",
    price: 99.99,
    description: "Voice-controlled speaker with virtual assistant integration.",
    color: "Gray",
    in_stock: true,
  },
  {
    id: 9,
    name: "External Hard Drive",
    brand: "Winz",
    price: 129.99,
    description: "Portable storage solution with high capacity.",
    color: "Black",
    in_stock: true,
  },
  {
    id: 10,
    name: "Action Camera",
    brand: "Nikon",
    price: 199.99,
    description: "Waterproof camera for capturing adventures.",
    color: "Red",
    in_stock: true,
  },
];

module.exports = { products };
