import Quotes from "../components/quotes";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.BoxTitle}>
        <h1>POKEDEX </h1>
        <Link href="/pokedex">
          <img
            className={styles.PokedexImg}
            src="https://cdn.dribbble.com/userupload/3875672/file/original-42f52449520e8e7940c668566888d84f.png?resize=752x"
            alt="Pokedex"
          />
        </Link>
      </div>
      <p className={styles.BoxPara}>Here's your Pokédex, click on it</p>
      <Quotes
        paragraph="«I see now that the circumstances of one's birth are irrelevant. It is what you do with the gift of life that determines who you are.»"
        title="Mewtwo"
        imageSrc="https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png"
      />
      <Quotes
        paragraph="«Take charge of your destiny»"
        title="Rayquaza"
        imageSrc="https://media.pokemoncentral.it/wiki/thumb/1/16/Artwork0384_ROZA.png/200px-Artwork0384_ROZA.png"
      />
    </>
  );
}
